### ISSUE TITLE
Are there compiled releases?

### ISSUE THREAD

**Issue by EmmanuelMess** [mgrabmueller/TransformersStepByStep#7]
Are there any compiled releases of this?

**Comment by mgrabmueller** [comment]
No, currently not. Right now, I don't have a working installation to create the PDF, but I will see what I can do.

**Comment by FranklinChen** [comment]
Perhaps document the process?

Here's how I generate PDF:

1. Install `lhs2tex`
2. Run `lhs2TeX Transformers.lhs > Transformers.tex`
3. Run `latexmk -pdf Transformers.tex` to get `Transformers.pdf`

**Comment by mgrabmueller** [comment]
Good idea! I will also extend the acknowledgements section and commit the PDF for archival purrposes.

**Comment by mgrabmueller** [comment]
You can now find the PDF in subdirectory pdf/
I also fixed a couple of mistakes, updated URLs and extended the acknowledgements section.
